name = "Cactus Plus Plus"
license = "MIT"
licenselink = "https://github.com/mbag/hugo-theme-cactus-plus-plus/blob/master/LICENSE.md"
description = "A minimalistic and responsive theme for bloggers."
homepage = "https://github.com/mbag/hugo-theme-cactus-plus-plus"
tags = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
features = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
min_version = 0.20

[author]
  name = "mbag"
  homepage = "https://github.com/mbag"

[[original]]
  name = "Cactus Plus"
  homepage = "https://themes.gohugo.io/cactus/"
  repo = "https://github.com/nodejh/hugo-theme-cactus-plus"
